### ISSUE TITLE
User can search a team

### ISSUE THREAD

**Issue by CTMendoza** [CTMendoza/AJAX-Project#1]
## ⚙️ Feature

> ##### User will be able to view a teams current roster

## 📐 Functionality

> ##### User can search up a specific NBA team and pull up a table of their current roster

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![ajax-project-feature 1 desktop](https://user-images.githubusercontent.com/90743100/190040858-17dbba71-eb7d-4aa5-8a8d-b2fb500efa7a.png)

![ajax-project-feature 1 mobile](https://user-images.githubusercontent.com/90743100/190040892-9c20bc56-9c9f-4603-94f0-82d6cf770e9e.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [ ] ... 
- [ ] Create a HTML template that includes a nav header section.
- [ ] create a text field to type in NBA team names and a 'search' button 
- [ ] create an 'click' event listener for the 'search' button so that when pressed, will generate a table of the team's current roster along other information about the players on the team
- [ ] create media querys that will allow responsiveness for the user to be able to view the web app on desktop and mobile
