### ISSUE TITLE
User can select and view player by season averages

### ISSUE THREAD

**Issue by CTMendoza** [CTMendoza/AJAX-Project#2]
## ⚙️ Feature

> ##### User will be able to view more information on a specific player

## 📐 Functionality

> ##### User can click on a specific player on a team's current roster and view a table of their statistical season averages

## 🖼️ Wireframes

![ajax-project-feature 2 desktop](https://user-images.githubusercontent.com/90743100/190041488-13695a04-8481-4c2d-b006-f8f347dc0a83.png)

![ajax-project-feature 2 mobile](https://user-images.githubusercontent.com/90743100/190041497-3c593fd2-e1c6-4bac-a365-cd2d767ea428.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [ ] ... 
- [ ]  make every players name on the current roster list clickable so that when clicked, the user will be able to view a new table of that players statistical season averages.
- [ ] create a table based on the player's season average stats in the DOM when the user clicks on a specific players name
- [ ] make a http request to the api to pull in the relevant data into each table
