### ISSUE TITLE
User can select and view a specific season

### ISSUE THREAD

**Issue by CTMendoza** [CTMendoza/AJAX-Project#3]
## ⚙️ Feature

> ##### The user will be able to view more specific player stats 

## 📐 Functionality

> ##### The user can click on a specific season and view a new table full of a the chosen player's stats for that season by each game they played

## 🖼️ Wireframes

![ajax-project-feature 3 desktop](https://user-images.githubusercontent.com/90743100/190042894-f49e6acb-ed24-4a60-9d33-3dfcbd151996.png)

![ajax-project-feature 3 mobile](https://user-images.githubusercontent.com/90743100/190042912-a616acd3-8146-4b3b-9908-c8f10844ca11.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [ ] make each season string in the table of a players seasonal averages clickable so that it will lead the user to a new table that details a players stats by that specific season clicked
- [ ] create a new table in the DOM when the user clicks a specific season 
- [ ] create an http request to the api to pull in relevant data into the table
