### ISSUE TITLE
User can save players to a favorites tab

### ISSUE THREAD

**Issue by CTMendoza** [CTMendoza/AJAX-Project#4]
## ⚙️ Feature

> ##### The user will be able to save and view their favorited players

## 📐 Functionality

> ##### The user can click a button to save the profile of a specific player to a table that keeps growing as the user saves more players

## 🖼️ Wireframes

![ajax-project-feature 4 desktop](https://user-images.githubusercontent.com/90743100/190043937-adda5cd5-52fe-498d-9854-a3da0c6068aa.png)

![ajax-project-feature 4 mobile](https://user-images.githubusercontent.com/90743100/190043946-fe5d6a94-ec68-4723-b387-624ecc0f2c47.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [ ] create a string called 'Favorites' in the nav header section of the html doc
- [ ] make the 'Favorites' string clickable so that the user can access their saved table of players
- [ ] create a button  at the bottom of the view of a players specific season that will save the profile of the player and create a new row of that players profile into the users favorites.
- [ ] when the button is clicked the user will also be taken to the view of their table of favorited players
